public class PatientWrapper {
    @AuraEnabled
    public String id;
     
    @AuraEnabled
    public String name;
    
    @AuraEnabled
    public Double steps;
   
    @AuraEnabled
    public Double goal;
    
    @AuraEnabled
    public Double heartRate;
    
    @AuraEnabled
    public Double height;
    
    @AuraEnabled
    public Double weight;
    
    @AuraEnabled
    public String patient_Id;
    
}